### ISSUE TITLE
如何获取自己的 client_id 和 client_secret

### ISSUE THREAD

**Issue by fanpest** [yanzai/goindex#10]
参照autorclone的教程获得了一个credentials.json的文件，里面有类似的client_id 和 client_secret，可是放入workers网页无法加载文件，是否我获取错误？

**Comment by he-sb** [comment]
~~使用 rclone 来获取 client_id 和 client_secret 。~~

使用默认的这两个参数默认值是 rclone 的，需要用自定义的需要去 Google 控制台自己开启。

**Comment by fanpest** [comment]
> ~使用 rclone 来获取 client_id 和 client_secret 。~
> 
> 使用默认的这两个参数默认值是 rclone 的，需要用自定义的需要去 Google 控制台自己开启。

懂了，https://developers.google.com/drive/api/v3/quickstart/java也要开启

**Comment by he-sb** [comment]
参考这个教程：

[GoIndex - 无服务器架构 Google Drive 目录索引程序 - P3TERX ZONE](https://p3terx.com/archives/goindex-google-drive-directory-index.html)

**Comment by yanzai** [comment]
需要在 google cloud 控制台开启 drive api ，这样才有权限去获取 drive 文件

**Comment by fanpest** [comment]
Ok,已经可以使用了，谢谢
