### ISSUE TITLE
[enhancement]给条目增加title

### ISSUE THREAD

**Issue by Ju-ch** [yanzai/goindex#12]
建议给文件列表的每个条目增加一个`title`，如下图：
![UTOOLS1587969164804.png](https://img01.sogoucdn.com/app/a/100520146/31dea94fa256a483b9e2fea502c2df8b)
部分文件名比较长，并且前缀相同的时候，除了看左下角的链接和文件大小，几乎无法分辨哪个是哪个。所以最好给每行加一个文件名的*title*。

**Comment by yanzai** [comment]
已添加。旧的 _4.23 版本可能需要强制刷新一下页面才能生效。

**Comment by Ju-ch** [comment]
赞👍🏻
