### ISSUE TITLE
文件在线预览问题

### ISSUE THREAD

**Issue by ceeim** [yanzai/goindex#13]
因原作者删库找到了这个版本，有一些小问题。
.mkv 格式在线预览，视频被预览为音频，或者有画面无声音，音量调节不可用，如图：
![image](https://user-images.githubusercontent.com/18570103/80409212-0af1a980-88fb-11ea-8faf-69b1e0a5f9a5.png)
![image](https://user-images.githubusercontent.com/18570103/80409308-396f8480-88fb-11ea-8357-a64e132a2aa9.png)
这些问题在原作者版本上从未出现过，应该是 BUG？
另外 README.md 、 HEAD.md 偶尔不显示（更新 4.28 又好了，可能是缓存问题？）

**Comment by ceeim** [comment]
以上问题在更新到最新 4.28 版本存在

**Comment by ceecx** [comment]
应该可以排除文件本身问题，因为使用外部播放器播放没问题。
以下是我这边出现问题的一些 .mkv 文件地址：
https://dl.cee.cx/0:/TVs/%E9%BB%91%E5%AE%A2%E5%86%9B%E5%9B%A2/

**Comment by leopardciaw** [comment]
@ceecx 借地请教下，如何部署到NAS上呢，给的链接不可用。

**Comment by woxinyi248** [comment]
4.28版本我也碰到了  调用外部播放器没问题

**Comment by yanzai** [comment]
视频播放器的逻辑跟原版 goindex 相同，没有更改过此部分的代码。
也就是说，在同一台设备的同一个浏览器下，同一个视频在原版 goindex 的表现和这个版本 goindex 的表现应该是一致的。
所以我不太确定你是如何得出的 "这些问题在原作者版本上从未出现过，应该是 BUG？" 的结论。你对比的是同一个视频么？

另外，mkv 文件一般都是内封了多条音轨、多个字幕的，web浏览器对 mkv 文件的播放本来就支持的不好，一般还是用专业一点的播放器来播放这些文件。

关于 README.md ，在所有分页全部加载完成后才会显示出来，因为显示 README 可能会影响下一页的加载，如果你是因为这一点显示不出来的，自行调整设置里每页大小

**Comment by ceeim** [comment]
> 所以我不太确定你是如何得出的 "这些问题在原作者版本上从未出现过，应该是 BUG？" 的结论。你对比的是同一个视频么？

的确是同一个视频，原版本没问题的。

**Comment by yanzai** [comment]
> 的确是同一个视频，原版本没问题的。

我下载了你发的链接中的一个 mkv 视频，然后用原版 goindex 和本版 goindex 分别部署了一个 worker：
原版 goindex:
https://mkv-test.java.workers.dev/
本版 goindex:
https://mkv-test2.java.workers.dev/0:/

请你测试一下，是否两边的播放体验不同。在我这里，都是播放不出来的。
原版 goindex 代码来源于一个较新的 fork ： https://github.com/5Lin/goindex

**Comment by ceeim** [comment]
我这边测试也是播放有问题，部分 mkv 可以打开，主要是想确认 mkv 文件在线预览的问题，之前的 mkv 是没有问题的，这几部是近几天上传的，但是当时有随意预览几个没问题，只是部分。可能是这几部影片的问题。

**Comment by ceeim** [comment]
mp4 暂时没发现问题，一切正常，但大多都是 mkv 很难受，片源的问题吧，这个质量比较高的可能要本地机器解码。

**Comment by ceeim** [comment]
经过多次测试的确是有部分 mkv 文件在线预览有画面无声音、音量调节不可用，但也有很多都是正常。。。可能和本身资源有关，还以为是偶发性的 BUG，看来应该不是，感谢 @yanzai 的热心，关闭 Issues，祝好。:)
