### ISSUE TITLE
Add CORS for files

### ISSUE THREAD

**Issue by churongcon** [yanzai/goindex#3]
Hello, How to add CORS for files 
I want to embed file but File has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header

**Comment by yanzai** [comment]
Upgrade to version _4.23 and set `enable_cors_file_down` to `true`, then you can make it.

https://github.com/yanzai/goindex/blob/f7130d656a1a35240dbeb78da7fcfc142de0fd62/index.js#L51
